#ifndef SURFACE_ARRAYS_H_
#define SURFACE_ARRAYS_H_

#include <SDL2/SDL.h>

enum BackgroundSurfaces 
{
	S_BACKGROUND,
	SURFACE_BACKGROUND_TOTAL	
};

enum BeaconSurfaces
{
	S_SPAWN_NEXT_SCENE_BEACON,
	SURFACE_BEACON_TOTAL
};

enum ButtonSurfaces
{
	S_PLAY_BUTTON_UNCLICKED,
	S_PLAY_BUTTON_HOVER,
	S_PLAY_BUTTON_CLICKED,
	SURFACE_BUTTON_TOTAL
};

enum CharacterSurfaces 
{
	S_CHARACTER_IDLE_RIGHT,
	S_CHARACTER_IDLE_LEFT,
	S_CHARACTER_WALKING_RIGHT,
	S_CHARACTER_WALKING_LEFT,
	S_CHARACTER_JUMPING_RIGHT,
	S_CHARACTER_JUMPING_LEFT, 
	SURFACE_CHARACTER_TOTAL
};


typedef struct SurfaceArrays 
{
	SDL_Surface* BackgroundSurfaces[SURFACE_BACKGROUND_TOTAL]; 
	SDL_Surface* BeaconSurfaces[SURFACE_BEACON_TOTAL];
	SDL_Surface* ButtonSurfaces[SURFACE_BUTTON_TOTAL];
	SDL_Surface* CharacterSurfaces[SURFACE_CHARACTER_TOTAL]; 
} SurfaceArrays;


#endif
